name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Garante permissões de escrita para o GITHUB_TOKEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Atualizado para a versão mais recente
      - name: Bump version and create changelog
        uses: undergroundwires/bump-everywhere@master
        with:
          user: 'KeepW0rk'
          git-token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'release'
